# Generated by Django 5.2.9 on 2026-01-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chai", "0002_chaivariety_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="chaivariety",
            name="price",
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
            preserve_default=False,
        ),
    ]
